### ISSUE TITLE
incorrect parse

### ISSUE THREAD

**Issue by tamtakoe** [sedenardi/stream-dbf#1]
Plugin incorrect parse http://gis-lab.info/data/vmap0-settl-rus/population-gislab.7z f.e. (a lot of fields are empty)

**Comment by sedenardi** [comment]
I've verified that it's reading the header of DBF files correctly, but I'm not sure why it's not parsing the records correctly according to the field lengths. When I debug "pop-built-up-a-gislab.dbf" I see that the records start to become corrupted after NEWID = 41.

Unfortunately, I don't have much time to dig into the issue right now. Additionally, this project was mostly a port of abstractvector's [node-dbf](https://github.com/abstractvector/node-dbf) project, so I'm assuming the bug persists in that module as well.

If you figure out a solution I welcome pull requests.

**Comment by tamtakoe** [comment]
I found only one plug-in that could read this database (and then had to fork it so that it supported the numeric type `float`). https://github.com/tamtakoe/node-dbf
Maybe it helps you

**Comment by sedenardi** [comment]
I figured out what the issue was. I was incorrectly concatenating buffers in the transform stream.

https://github.com/sedenardi/stream-dbf/commit/2ae727743451dfa1f2c3d4df6297f5babedeb9df

I've updated the package in npm to 0.1.2 with the fix. Thanks for bringing this issue to light.
