### ISSUE TITLE
Wrong length for only one field in database

### ISSUE THREAD

**Issue by nulltier** [sedenardi/stream-dbf#5]
I have a dbf file. All works fine except one field named «NOM». I know that it's length is 300 charanters, but this library has other opinion. It thinks that field is only 44 characters long. Тherefore, everything that does not fit in that 44 character trimmed. 

![image](https://cloud.githubusercontent.com/assets/862521/8481535/49c45526-20ec-11e5-8e0a-c5ad7f7cac54.png)

I know that this library is open source and we all have limited time to support projects like this. But anyway I've attached file with that database in hope that, maybe, you'll find time and motivation to get a glance in it. https://yadi.sk/d/XJdHxVZ-hdMYH

**Comment by sedenardi** [comment]
Is this still an issue? If so, I'll happily accept a pull-request.
